version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - '3306:3306'
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - db
    ports:
      - '8080:80'
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
