version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_SSL_CERT: /etc/ssl/certs/pazijaya.my.id.crt
      MYSQL_SSL_KEY: /etc/ssl/private/pazijaya.my.id.key
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    image: laravelapp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private

volumes:
  db_data:
